// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthStarET.NextGen.Lms.Infrastructure.Districts.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NorthStarET.NextGen.Lms.Infrastructure.Districts.Persistence.Migrations
{
    [DbContext(typeof(DistrictsDbContext))]
    [Migration("20251025215148_InitialDistricts")]
    partial class InitialDistricts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("districts")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NorthStarET.NextGen.Lms.Domain.Auditing.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ActorId");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ActorRole");

                    b.Property<string>("AfterPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("AfterPayload");

                    b.Property<string>("BeforePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("BeforePayload");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("CorrelationId");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("DistrictId");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("EntityType");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TimestampUtc");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditRecords_CorrelationId");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("IX_AuditRecords_DistrictId");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("IX_AuditRecords_TimestampUtc");

                    b.HasIndex("DistrictId", "ActorId")
                        .HasDatabaseName("IX_AuditRecords_DistrictId_ActorId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditRecords_EntityType_EntityId");

                    b.ToTable("AuditRecords", "districts");
                });

            modelBuilder.Entity("NorthStarET.NextGen.Lms.Domain.DistrictAdmins.DistrictAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("DistrictId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("InvitedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("InvitedAtUtc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RevokedAtUtc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VerifiedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("IX_DistrictAdmins_DistrictId");

                    b.HasIndex("InvitedAtUtc")
                        .HasDatabaseName("IX_DistrictAdmins_InvitedAtUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DistrictAdmins_Status");

                    b.HasIndex("DistrictId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_DistrictAdmins_DistrictId_Email_Unique");

                    b.ToTable("DistrictAdmins", "districts");
                });

            modelBuilder.Entity("NorthStarET.NextGen.Lms.Domain.Districts.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Suffix");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Districts_DeletedAt");

                    b.HasIndex("Suffix")
                        .IsUnique()
                        .HasDatabaseName("IX_Districts_Suffix_Unique")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Districts", "districts");
                });

            modelBuilder.Entity("NorthStarET.NextGen.Lms.Domain.DistrictAdmins.DistrictAdmin", b =>
                {
                    b.HasOne("NorthStarET.NextGen.Lms.Domain.Districts.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
