// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthStarET.NextGen.Lms.Infrastructure.Districts.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NorthStarET.NextGen.Lms.Infrastructure.Districts.Persistence.Migrations
{
    [DbContext(typeof(DistrictsDbContext))]
    [Migration("20251112000614_AddSchoolsAndGradeOfferings")]
    partial class AddSchoolsAndGradeOfferings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("districts")
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NorthStarET.NextGen.Lms.Domain.Auditing.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ActorId");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ActorRole");

                    b.Property<string>("AfterPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("AfterPayload");

                    b.Property<string>("BeforePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("BeforePayload");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("CorrelationId");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("DistrictId");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("EntityType");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TimestampUtc");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditRecords_CorrelationId");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("IX_AuditRecords_DistrictId");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("IX_AuditRecords_TimestampUtc");

                    b.HasIndex("DistrictId", "ActorId")
                        .HasDatabaseName("IX_AuditRecords_DistrictId_ActorId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditRecords_EntityType_EntityId");

                    b.ToTable("AuditRecords", "districts");
                });

            modelBuilder.Entity("NorthStarET.NextGen.Lms.Domain.DistrictAdmins.DistrictAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("DistrictId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("InvitedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("InvitedAtUtc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RevokedAtUtc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VerifiedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("IX_DistrictAdmins_DistrictId");

                    b.HasIndex("InvitedAtUtc")
                        .HasDatabaseName("IX_DistrictAdmins_InvitedAtUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DistrictAdmins_Status");

                    b.HasIndex("DistrictId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_DistrictAdmins_DistrictId_Email_Unique");

                    b.ToTable("DistrictAdmins", "districts");
                });

            modelBuilder.Entity("NorthStarET.NextGen.Lms.Domain.Districts.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Suffix");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Districts_DeletedAt");

                    b.HasIndex("Suffix")
                        .IsUnique()
                        .HasDatabaseName("IX_Districts_Suffix_Unique")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Districts", "districts");
                });

            modelBuilder.Entity("NorthStarET.NextGen.Lms.Domain.Schools.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Schools_DeletedAt");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("IX_Schools_DistrictId");

                    b.HasIndex("DistrictId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Schools_DistrictId_Code_Unique")
                        .HasFilter("[Code] IS NOT NULL AND [DeletedAt] IS NULL");

                    b.HasIndex("DistrictId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Schools_DistrictId_Name_Unique")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("Schools", "districts");
                });

            modelBuilder.Entity("NorthStarET.NextGen.Lms.Domain.DistrictAdmins.DistrictAdmin", b =>
                {
                    b.HasOne("NorthStarET.NextGen.Lms.Domain.Districts.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NorthStarET.NextGen.Lms.Domain.Schools.School", b =>
                {
                    b.OwnsMany("NorthStarET.NextGen.Lms.Domain.Schools.GradeOffering", "GradeOfferings", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("ConcurrencyStamp")
                                .IsConcurrencyToken()
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EffectiveFrom")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("EffectiveTo")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("GradeLevel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<Guid>("SchoolId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SchoolType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTime?>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SchoolId", "EffectiveTo")
                                .HasDatabaseName("IX_GradeOfferings_SchoolId_EffectiveTo");

                            b1.ToTable("GradeOfferings", "districts");

                            b1.WithOwner()
                                .HasForeignKey("SchoolId");
                        });

                    b.Navigation("GradeOfferings");
                });
#pragma warning restore 612, 618
        }
    }
}
