# GitHub Copilot Coding Agent Setup Steps
# This file defines the environment setup for Copilot coding agent on self-hosted runners
# Documentation: https://docs.github.com/en/enterprise-cloud@latest/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment

name: Copilot Coding Agent Setup

on:
  copilot_coding_agent_workflow_run

jobs:
  setup:
    runs-on: arc-runner-set  # Our ARC runner with .NET 10 + Aspire
    
    steps:
      # CRITICAL: Set GITHUB_HOST to fix CodeQL "GitHub host is required" error
      # This must be set via $GITHUB_ENV, not job-level env (per GitHub community discussion)
      - name: Set GitHub host for CodeQL
        shell: pwsh
        run: |
          "GITHUB_HOST=github.com" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
      # Set tools directory for pre-installed CodeQL (if applicable)
      - name: Configure tools directory
        shell: pwsh
        run: |
          "AGENT_TOOLSDIRECTORY=D:\hostedtoolcache" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
      # Checkout the repository
      - uses: actions/checkout@v4
      
      # Verify .NET 10 is available
      - name: Verify .NET 10
        shell: pwsh
        run: |
          dotnet --version
          dotnet workload list
      
      # Restore .NET dependencies
      - name: Restore dependencies
        shell: pwsh
        run: dotnet restore
      
      # Verify Docker is available for Aspire
      - name: Verify Docker
        shell: pwsh
        run: |
          docker --version
          docker compose version
      
      # Verify Node.js for MCP servers
      - name: Verify Node.js
        shell: pwsh
        run: node --version
      
      # Install Aspire CLI if not already available
      - name: Install Aspire CLI
        shell: pwsh
        run: |
          try { dotnet tool install -g Aspire.Hosting.Orchestration.Web -ErrorAction SilentlyContinue } catch {}
          dotnet tool restore
      
      # Verify MCP servers are accessible
      - name: Verify MCP Servers
        shell: pwsh
        run: |
          Write-Host "MCP servers will be started automatically by the Copilot agent"
          Write-Host "Configured servers:"
          Write-Host "- sequential-thinking: @modelcontextprotocol/server-sequential-thinking"
          Write-Host "- filesystem: @modelcontextprotocol/server-filesystem"
          Write-Host "- microsoft-docs: @microsoft/mcp-server-docs"
