using NorthStarET.NextGen.Lms.Domain.Common;
using NorthStarET.NextGen.Lms.Domain.Common.Interfaces;

namespace NorthStarET.NextGen.Lms.Domain.Districts;

/// <summary>
/// District aggregate root representing a tenant grouping with unique email domain suffix.
/// Implements soft-delete pattern and emits domain events for lifecycle changes.
/// </summary>
public sealed class District : AggregateRoot
{
    private District(Guid id, string name, string suffix, DateTime createdAtUtc)
        : base(id)
    {
        Name = name;
        Suffix = suffix;
        CreatedAtUtc = createdAtUtc;
    }

    /// <summary>
    /// District display name (3-100 characters, trimmed).
    /// </summary>
    public string Name { get; private set; }

    /// <summary>
    /// Unique case-insensitive email domain suffix (e.g., "demo" for demo.example.edu).
    /// Must match regex ^[a-z0-9.-]+$ and be unique platform-wide.
    /// </summary>
    public string Suffix { get; private set; }

    /// <summary>
    /// UTC timestamp when the district was created.
    /// </summary>
    public DateTime CreatedAtUtc { get; private set; }

    /// <summary>
    /// UTC timestamp when the district was last updated (nullable).
    /// </summary>
    public DateTime? UpdatedAtUtc { get; private set; }

    /// <summary>
    /// UTC timestamp when the district was soft-deleted (nullable).
    /// When set, triggers cascade revoke for all district admins.
    /// </summary>
    public DateTime? DeletedAt { get; private set; }

    /// <summary>
    /// Indicates whether the district is in a soft-deleted state.
    /// </summary>
    public bool IsDeleted => DeletedAt.HasValue;

    /// <summary>
    /// Factory method to create a new District with validation.
    /// Emits DistrictCreated domain event.
    /// </summary>
    /// <param name="id">Unique identifier for the district</param>
    /// <param name="name">District name (3-100 chars, will be trimmed)</param>
    /// <param name="suffix">Email domain suffix (lowercase, must match ^[a-z0-9.-]+$)</param>
    /// <param name="dateTimeProvider">Date time provider for current time</param>
    /// <returns>New District instance</returns>
    /// <exception cref="ArgumentException">Thrown when validation fails</exception>
    public static District Create(Guid id, string name, string suffix, IDateTimeProvider dateTimeProvider)
    {
        ValidateName(name);
        ValidateSuffix(suffix);

        var district = new District(
            id,
            name.Trim(),
            suffix.ToLowerInvariant(),
            dateTimeProvider.UtcNow
        );

        district.RaiseDomainEvent(new DistrictCreatedEvent(
            district.Id,
            district.Name,
            district.Suffix,
            district.CreatedAtUtc
        ));

        return district;
    }

    /// <summary>
    /// Convenience factory for scenarios where the identifier is generated by the domain.
    /// </summary>
    /// <param name="name">District name</param>
    /// <param name="suffix">Email domain suffix</param>
    /// <param name="dateTimeProvider">Date time provider for current time</param>
    /// <returns>New District instance</returns>
    public static District Create(string name, string suffix, IDateTimeProvider dateTimeProvider)
        => Create(Guid.NewGuid(), name, suffix, dateTimeProvider);

    /// <summary>
    /// Updates district name and/or suffix with validation.
    /// Emits DistrictUpdated domain event.
    /// </summary>
    /// <param name="name">New district name</param>
    /// <param name="suffix">New email domain suffix</param>
    /// <param name="dateTimeProvider">Date time provider for current time</param>
    public void Update(string name, string suffix, IDateTimeProvider dateTimeProvider)
    {
        if (IsDeleted)
        {
            throw new InvalidOperationException("Cannot update a deleted district.");
        }

        ValidateName(name);
        ValidateSuffix(suffix);

        var oldName = Name;
        var oldSuffix = Suffix;

        Name = name.Trim();
        Suffix = suffix.ToLowerInvariant();
        UpdatedAtUtc = dateTimeProvider.UtcNow;

        RaiseDomainEvent(new DistrictUpdatedEvent(
            Id,
            oldName,
            Name,
            oldSuffix,
            Suffix,
            UpdatedAtUtc.Value
        ));
    }

    /// <summary>
    /// Performs soft delete on the district.
    /// Emits DistrictDeleted domain event which triggers cascade revoke for all admins.
    /// </summary>
    /// <param name="dateTimeProvider">Date time provider for current time</param>
    public void Delete(IDateTimeProvider dateTimeProvider)
    {
        if (IsDeleted)
        {
            throw new InvalidOperationException("District is already deleted.");
        }

        DeletedAt = dateTimeProvider.UtcNow;

        RaiseDomainEvent(new DistrictDeletedEvent(
            Id,
            Name,
            Suffix,
            DeletedAt.Value
        ));
    }

    /// <summary>
    /// Restores a soft-deleted district (for recovery scenarios).
    /// </summary>
    /// <param name="dateTimeProvider">Date time provider for current time</param>
    public void Restore(IDateTimeProvider dateTimeProvider)
    {
        if (!IsDeleted)
        {
            throw new InvalidOperationException("District is not deleted.");
        }

        DeletedAt = null;
        UpdatedAtUtc = dateTimeProvider.UtcNow;
    }

    private static void ValidateName(string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name, nameof(name));

        var trimmedName = name.Trim();
        if (trimmedName.Length < 3 || trimmedName.Length > 100)
        {
            throw new ArgumentException(
                "District name must be between 3 and 100 characters.",
                nameof(name)
            );
        }
    }

    private static void ValidateSuffix(string suffix)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(suffix, nameof(suffix));

        var lowerSuffix = suffix.ToLowerInvariant();

        // Validate pattern: lowercase alphanumeric, dots, and hyphens only
        if (!System.Text.RegularExpressions.Regex.IsMatch(lowerSuffix, @"^[a-z0-9.-]+$"))
        {
            throw new ArgumentException(
                "Suffix must contain only lowercase letters, numbers, dots, and hyphens.",
                nameof(suffix)
            );
        }

        if (lowerSuffix.Length < 2 || lowerSuffix.Length > 50)
        {
            throw new ArgumentException(
                "Suffix must be between 2 and 50 characters.",
                nameof(suffix)
            );
        }
    }
}

/// <summary>
/// Domain event raised when a new district is created.
/// </summary>
/// <param name="DistrictId">ID of the created district</param>
/// <param name="Name">District name</param>
/// <param name="Suffix">Email domain suffix</param>
/// <param name="CreatedAtUtc">Creation timestamp</param>
public sealed record DistrictCreatedEvent(
    Guid DistrictId,
    string Name,
    string Suffix,
    DateTime CreatedAtUtc
) : IDomainEvent;

/// <summary>
/// Domain event raised when a district is updated.
/// </summary>
public sealed record DistrictUpdatedEvent(
    Guid DistrictId,
    string OldName,
    string NewName,
    string OldSuffix,
    string NewSuffix,
    DateTime UpdatedAtUtc
) : IDomainEvent;

/// <summary>
/// Domain event raised when a district is soft-deleted.
/// Triggers cascade revoke for all district admins.
/// </summary>
public sealed record DistrictDeletedEvent(
    Guid DistrictId,
    string Name,
    string Suffix,
    DateTime DeletedAt
) : IDomainEvent;
