using System;
using System.Collections.Generic;
using NorthStarET.NextGen.Lms.Application.Common.Behaviors;

namespace NorthStarET.NextGen.Lms.Bdd.Support;

/// <summary>
/// Collects audit records emitted during scenario execution to assert against expectations.
/// </summary>
public sealed class TestAuditSink
{
    private readonly List<AuditRecordSnapshot> _records = new();

    public IReadOnlyList<AuditRecordSnapshot> Records => _records.AsReadOnly();

    public void Capture(IAuditableCommand command)
    {
        ArgumentNullException.ThrowIfNull(command);

        _records.Add(new AuditRecordSnapshot(
            command.Action,
            command.EntityType,
            command.EntityId,
            command.BeforePayload,
            command.AfterPayload));
    }

    public void Clear() => _records.Clear();
}

/// <summary>
/// Lightweight representation of an audit record generated by a command.
/// </summary>
public sealed record AuditRecordSnapshot(
    string Action,
    string EntityType,
    Guid? EntityId,
    string? BeforePayload,
    string? AfterPayload);
