// <auto-generated />
namespace NorthStar.EF6.LoginDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class assessmentname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(assessmentname));
        
        string IMigrationMetadata.Id
        {
            get { return "201612050113491_assessmentname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
