// <auto-generated />
namespace NorthStar.EF6.LoginDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class batchpring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(batchpring));
        
        string IMigrationMetadata.Id
        {
            get { return "201609052123181_batchpring"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
