// <auto-generated />
namespace NorthStar.EF6.DistrictContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class displayinresultslist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(displayinresultslist));
        
        string IMigrationMetadata.Id
        {
            get { return "201604291133167_displayinresultslist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
