// <auto-generated />
namespace NorthStar.EF6.DistrictContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class staffandimportcolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(staffandimportcolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201605241153388_staffandimportcolumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
